version: '3.8'

services:
  php:
    image: ysj/php-fpm:0.0.1
    container_name: php
    build:
        context: ./app
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    command:  php-fpm -F --pid "/opt/bitnami/php/tmp/php-fpm.pid" -y "/usr/local/etc/php-fpm.conf"
  nginx:
    image: nginx
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - 8089:80
    depends_on:
      - php