version: '3.8'

services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos-standalone-sqlite
    # env_file:
    #   - ../env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"