name: docker-symfony-demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!

      - name: clone toy-store
        run: cd docker-symfony-demo 
           && sh toy-store-deploy.sh
           && docker-composer up -d
